<!DOCTYPE html> 
<html>
        <title>
            Test
        </title>
    </head>

    <body>
    <p>I'm <?= $authGateway->getUser()['login'] ?></p>

    <p><?php include "logout.phtml" ?></p>

    <p><b>Текст: </b><?= $text; ?> </p>

         <form action="" method="post">
            
            <p> Text: <textarea name="text"></textarea></p>            
            <p><input type="submit"> </p>
         </form>    

         <?php foreach($newComments as $item){ ?>
            <p><?= $item['data']?> 
                <?= $item['author']?> :
                <?= $item['text']?> </P>
        <?php } ?>
    </body>
</html>