<html>
    <head>
        <title>
            Test
        </title>
    </head>

    <body>

    <p><b>Текст: </b><?= $name; ?> </p>

         <form action="" method="post">
            <p> Author: <textarea name= "author"></textarea>  </p> 
            <p> Name: <textarea name="name"></textarea></p>            
            <p><input type="submit"> </p>
            <?php foreach($nameList as $item){ ?>
                <p><?= $item['data']?> 
                    <?= $item['author']?> :
                    <?= $item['name']?> </P>
            <?php } ?>

         </form>
        

    </body>
</html>