<html>
    <head>
        <title>
            Test
        </title>
    </head>

    <body>
<p><?php include "logout.phtml" ?></p>

    <p><b>Текст: </b><?= $name; ?> </p>

         <form action="" method="post">
            
            <p> Name: <textarea name="name"></textarea></p>            
            <p><input type="submit"> </p>
         </form>    

         <?php foreach($newComments as $item){ ?>
            <p><?= $item['data']?> 
                <?= $item['author']?> :
                <?= $item['name']?> </P>
        <?php } ?>
    </body>
</html>